name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Eller den branch du vill deploya från

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Använd den Node.js-version du behöver

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build  # Byggprocessen måste skapa en dist-mapp med dina produktionstillgångar

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Ditt byggskript bör outputa filer här
